spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ToDoBase
    username: postgres
    password: 420875ff
  security:
    user:
      name: Revan
      password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
